# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildFatJarForJVM:
    name: Build JVM jar application
    runs-on: ubuntu-latest
    outputs:
      tag-version: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      # - name: Use Gradle packages cache
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.gradle/caches/
      #       ~/.gradle/wrapper/
      #     key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      #     restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Bump version and push tag
        if: ${{ github.ref == 'refs/heads/main' }}
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
      - name: Build with Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TFDB_APIKEY: ${{ secrets.TFDB_APIKEY }}
          PREMIUMIZE_APIKEY: ${{ secrets.PREMIUMIZE_APIKEY }}
          ALLDEBRID_APIKEY: ${{ secrets.ALLDEBRID_APIKEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: ./gradlew build
      - uses: actions/upload-artifact@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          name: jvmArtifacts-${{ github.sha }}
          path: |
            ./build/libs/boat.jar
          retention-days: 1
  # buildFatJarForGraalVM:
  #   name: Build GraalVM jar application
  #   runs-on: ubuntu-latest
  #   continue-on-error: true
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - uses: ayltai/setup-graalvm@v1
  #       with:
  #         java-version: 17
  #         graalvm-version: 22.0.0.2
  #         native-image: true
  #     - run: java -version
  #     - name: Build with Gradle (GraalVM)
  #       env:
  #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #          TFDB_APIKEY: ${{ secrets.TFDB_APIKEY }}
  #          PREMIUMIZE_APIKEY: ${{ secrets.PREMIUMIZE_APIKEY }}
  #          ALLDEBRID_APIKEY: ${{ secrets.ALLDEBRID_APIKEY }}
  #       run: ./gradlew assemble
  #     - run: native-image --no-fallback --allow-incomplete-classpath -jar "./build/libs/boat.jar" boatImage
  #     - uses: actions/upload-artifact@v4
  #       if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
  #       with:
  #         name: graalVmArtifacts-${{ github.sha }}
  #         path: |
  #           ./boatImage
  #         retention-days: 1
  releaseJob:
    name: Create Github Release
    runs-on: ubuntu-latest
    needs: [buildFatJarForJVM]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v5
        with:
          name: jvmArtifacts-${{ github.sha }}
      - name: Release
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.buildFatJarForJVM.outputs.tag-version }}
          files: |
            boat.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  restartServerJob:
    name: Restart the Server
    runs-on: ubuntu-latest
    needs: [releaseJob]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Restart server
        run: curl ${{ secrets.SERVERURL }}/boat/shutdown|| true
